import Head from "next/head";
import LandingPage from "./LandingPage";
import axios from "axios";

axios.defaults.baseURL = "http://localhost:4000/api";
axios.defaults.withCredentials = true;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingPage />
      </main>
    </>
  );
}
